apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: elasticsearch-logging-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: elasticsearch-logging-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch-logging-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
