---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}    
  annotations:
    description: "This is my ui pod"  
spec:
  replicas: 3
  # стратегия Recreate означает, что в случае обновления все старые поды будут остановлены, а затем запущены новые, что может привести к временной недоступности приложения на время пересоздания подов
  strategy:
    type: Recreate
  # поле которое определяет, какие объекты Kubernetes будут управляться данным ресурсом
  # В данном случае - контроллер будет считать POD-ы с метками: app=reddit И component=ui. Поэтому важно в описании POD-а (секция template) задать нужные метки (labels)
  selector:
    matchLabels:
      app: reddit
      component: ui
      release: {{ .Release.Name }}      
  # Здесь задается шаблон pod     
  template:
    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
        release: {{ .Release.Name }}        
    spec:
      containers:
      - image: vasiliybasov/ui:latest
        name: ui
        # определяет порт, который будет использоваться для связи с контейнером.
        ports:
        # Это параметр контейнера в Kubernetes, который определяет порт, на котором контейнер должен слушать входящие соединения. 
        # Таким образом, приложение, работающее в контейнере, будет доступно на этом порту внутри кластера Kubernetes, 
        # а также снаружи кластера, если соответствующие правила доступа настроены.
        - containerPort: 9292
          name: ui
          protocol: TCP        
        # в данном примере переменная окружения ENV будет содержать значение равное названию пространства имен,
        # в котором находится данный Pod. Например, если этот Pod находится в пространстве имен dev, 
        # то значение переменной окружения ENV будет равно dev.
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace        
      imagePullSecrets:
      - name: regcred