---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongo-pvc-dynamic
spec:
  # Том может быть смонтирован в режиме чтения-записи только на одном узле (node) в кластере Kubernetes
  accessModes:
    - ReadWriteOnce
  # Создаем PersistentVolumeClaim ссылаясь на созданный нами StorageClass storage-fast.yml Вместо ссылки на созданный диск.
  storageClassName: {{ .Release.Name }}-fast
  resources:
    requests:
      storage: 10Gi
