version: '3.3'
services:
  # Имя контейнера аналог docker run --name post-db
  post_db:
    # Use MongoDB image with version specified in MONGODB_VERSION env variable
    image: mongo:${MONGODB_VERSION}
    # Use existing volume named reddit_db, этот volume мы создавали раньше
    volumes:
      - reddit_db:/data/db
    # Connect to back_net network and give container the aliases post_db and comment_db  
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  post:
    # Set the image name to ${USERNAME}/post:${POST_VERSION}
    image: ${USER_NAME}/post:${POST_VERSION}
    # Connect to back_net network and give container the alias post
    environment:
      # Имя контейнера с базой данных
      - POST_DATABASE_HOST=post_db
      # Имя базы данных
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}      
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    # Определяем драйвер логирования для сервиса post вместо драйвера по умолчанию 
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
        aliases:
          - post
      # Connect to front_net network and give container the alias post    
      front_net:
        aliases:
          - post        
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    # Connect to back_net and front_net network with the alias comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}    
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment  
  ui:
    # Set the image name to ${USER_NAME}/ui:${UI_VERSION}
    image: ${USER_NAME}/ui:${UI_VERSION}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}    
    # Expose port ${UI_PORT} and map it to the container's 9292/tcp port
    ports:
      - target: 9292 # the port inside the container
        published: ${UI_PORT} # the publicly exposed port
        protocol: tcp # the port protocol (tcp or udp)
        mode: host # host for publishing a host port on each node, or ingress for a swarm mode port to be load balanced.
    depends_on:
      - post        
    # Connect to front_net network
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui


volumes:
  reddit_db:
    # Declare reddit_db as external volume означает то что он у нас уже существует а не создается новый
    # external: true
    name: reddit_db

networks:
  back_net:
    # Use bridge driver for back_net network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    # Use bridge driver for front_net network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
