---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: reddit
    component: post
    release: {{ .Release.Name }}
#   annotations:
#     description: "This is my post pod"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: post
      release: {{ .Release.Name }}
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: post
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: post
          protocol: TCP
        env:
        # определяем значение переменной POST_DATABASE_HOST (адрес либо имя с базой данных mongo для post) которая будет равна либо значению в values.yaml (например внешняя база данных)
        # либо если значение не задано '<название релиза>-mongodb' это значение соответствует адресу базы, поднятой внутри релиза
        - name: POST_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name)}}      
      imagePullSecrets:
      - name: regcred
