---
apiVersion: v1
kind: Service
metadata:
  # В DNS появится запись для {{ .Release.Name }}-{{ .Chart.Name }}. Что бы узнать ip адрес: kubectl get svc post
  name: {{ template "comment.fullname" . }}
  # Метки для сервиса post: "app: reddit" и "component: post"
  labels:
    app: reddit
    component: post
    release: {{ .Release.Name }} # помечаем что сервис из конкретного релиза    
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }} # эта переменная берется из файла values.yaml
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }} # перенаправляет трафик на internalPort в поды, которые имеют метки "app: reddit" и "component: post", release: {{ .Release.Name }}
  # Это означает, что любой трафик, направленный на сервис post:internalPort будет автоматически распределен между подами, которые соответствуют меткам селектора.
  selector:
    app: reddit
    component: post
    release: {{ .Release.Name }}
