---
service:
  internalPort: 9292
  externalPort: 9292

image:
  repository: vasiliybasov/ui
  tag: latest

ingress:
  class: nginx
  host: cluster.basov.world

postHost:
postPort:
commentHost:
commentPort:
