---
service:
  internalPort: 9292
  externalPort: 9292

image:
  repository: vasiliybasov/ui
  tag: latest

ingress:
  class: nginx
  # host: "{{ .Release.Name }}.gitlab.basov.world"

postHost:
postPort:
commentHost:
commentPort:
