{
 "title": "Telegraf Docker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Containers Stopped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_stopped" }
   ]
  },
  {
   "title": "Net rx / tx bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_container_net_rx_bytes" },
    { "expr": "docker_container_net_tx_bytes" }
   ]
  },
  {
   "title": "Memory Usage Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent"
    }
   ]
  }
 ]
}