---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: dev
spec:
  storageClassName: pdbalanced
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # Если объем PV будет больше чем PVC то PVC все равно займет весь имеющийся объем.
      storage: 15Gi
  selector:
    matchLabels:
      storage-class: pdbalanced
