---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: test
  annotations:
    description: "This is my post pod"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post
      labels:
        app: post
    spec:
      containers:
      - image: vasiliybasov/post:latest
        name: post
      imagePullSecrets:
      - name: regcred