---
global:
  # С какой частотой собирать метрики
  scrape_interval: '5s'

# jobs объединяют в группы endpoint-ы выполняющие одинаковую функцию
# Конфигурация для опроса серверов:
scrape_configs:
  # Имя для задачи опроса Prometheus сервера:
  - job_name: 'prometheus'
    static_configs:
      # Сервер Prometheus для опроса:
      - targets:
            # Адреса для сбора метрик
          - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
          - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
          - 'comment:9292'
          
  - job_name: 'post'
    static_configs:
      - targets:
          - 'post:5000'          

  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: 
        - 'mongodb-exporter:9216'

  - job_name: 'docker'
    static_configs:
    - targets:
      - '10.0.1.1:9323'        

  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']

# https://github.com/prometheus/blackbox_exporter
# мониторинг по принципу черного ящика. Т.е. например мы можем проверить отвечает ли сервис по http, или принимает ли соединения порт.
  - job_name: 'blackbox'
  # Путь для получения метрик из blackbox exporter
    metrics_path: /probe
    params:
      module: 
        - http_2xx # Look for a HTTP 200 response.
        - icmp
    static_configs:
      - targets:
        - http://comment:9292/metrics
        - ui:9292
    # Relabeling configuration for the targets    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # The blackbox exporter's real hostname:port.

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
